id: account_settings
title: GovReady Account Settings
type: account
introduction:
  format: markdown
  template: |
    Hi,

    GovReady Q works much better when you have a user profile. 

    Answer a few  quick questions and will have your profile.
questions:
  - id: name
    title: Your Name
    prompt: What is your name?
    type: text

  - id: title
    title: Your Title
    prompt: What is your title in your organization or on this project?
    type: text

  - id: role
    title: Your Role
    prompt: Which team is your position most closely aligned?
    type: choice
    choices:
      - key: ceo_team
        text: CEO Team
        help: CEO, Agency Head, Chief of Staff, Special Advisor, ...
      - key: it_exec_team
        text: IT Executive Team
        help: Authorizing Official, AO Designated Representative, CIO, CISO, ...
      - key: dev_team
        text: Development Team
        help: Developer, Engineer, Project Manager, Architect, Agile Lead, Analyst, ...
      - key: ops_team
        text: Operations Team
        help: System Administrator, Engineer, Operations Manager, Delivery Specialist, ...
        key: sec_team
        text: Security Team
        help: Security Specialist, Architect, Security Manager, ...
      - key: comp_team
        text: Compliance Team
        help: Information System Security Officer, Information System Security Manager, Compliance Specialist, ...
      - key: audit_team
        text: Audit Team
        help: Security Control Assessor, Auditor, Inspector General, ...

  - id: picture
    title: Picture
    prompt: Optionally upload a photo of yourself.
    type: file
    file-type: image
    image:
      max-size:
        width: 640
        height: 640

  - id: chat
    title: Your Chat Application
    prompt: What chat application would you like to use to discuss your answers with your colleagues?
    type: choice
    choices:
      - key: slack
        text: Slack
        help: Slack.com is a great service!
      - key: skype
        text: Skype
        help: We like Skype too.
output:
  - title: Your Settings
    format: markdown
    template: |
      Here are your account settings:

      ### About You

      {% if picture %}
      ![Your Picture]({{picture.url}})
      {% endif %}

      {{name}}, {{title}}, is a member of the {{role.text}} at {{organization}}.

      ---

      ### Applications

      Chat: {{chat.text}}

      ### Account Settings

      [Change Your Password](/accounts/password/change/)
      
