# GovReady App (C) 2020 GovReady PBC (License GPLv3)
# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
# GovReady App (C) 2020 GovReady PBC (License GPLv3)
  govready-q:
    image: govready/govready-q
    hostname: govready-q
    restart: always
    ports:
      - "8000:8000"
    environment:
      - HOST=localhost
      - PORT=8000
      - HTTPS=false
      - DBURL=

  # Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
  wazuh:
    image: wazuh/wazuh:3.9.5_7.2.1
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.9.5_7.2.1
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    image: wazuh/wazuh-kibana:3.9.5_7.2.1
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  nginx:
    image: wazuh/wazuh-nginx:3.9.5_7.2.1
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana
