version: '3'
networks:
  q_network:
    driver: bridge

services:
  govready-q:
    container_name: govready_q
    build:
      context: ../..
      dockerfile: deployment/local/Dockerfile
    command: /bin/bash -c /usr/src/app/deployment/local/docker-entrypoint.sh
    env_file:
      - govready-q.env
    volumes:
      - ../..:/usr/src/app
    ports:
      - "8000:8000"
      - "2222:22"
    stdin_open: true
    tty: true
    restart: always
    networks:
      - q_network